### PR TITLE
Update SentryIo workflow to support extra operations

### PR DESCRIPTION
**Pull request by MedAliMarz**
this pr update workflow to support:

- Team: update delete
- Organization: update
- Release: update delete
- Project: create update delete

Note: this workflow will rely on the changes included in Sentry.io node through this [pr](https://github.com/n8n-io/n8n/pull/1605)

### CODE REVIEW

**Comment by krynble** [comment]
Hi @MedAliMarz 

The final 2 branches that relate to Issue and Events are not running as the `Get all` operations are not returning anything.

Could you please check? It seems like the project slug is wrong.

**Comment by MedAliMarz** [comment]
> Hi @MedAliMarz
> 
> The final 2 branches that relate to Issue and Events are not running as the `Get all` operations are not returning anything.
> 
> Could you please check? It seems like the project slug is wrong.

Fixed the project slug.

**Comment by krynble** [comment]
Thanks a lot!

**Comment by krynble** [comment]
Oh @MedAliMarz after merging I realized that the `delete` operation for the `Issue` resource was not present.

Could you please implement this in another PR?

Thanks again!

**Comment by MedAliMarz** [comment]
> Oh @MedAliMarz after merging I realized that the `delete` operation for the `Issue` resource was not present.
> 
> Could you please implement this in another PR?
> 
> Thanks again!

Sure thing. but the issue is manually generated (through generate sample event button), thus removing it will stop the further workflow executions.

**Pull request merged**
